#!/usr/bin/env python3
"""Create Wave Terminal console blocks for the local CML2 breakout proxy."""

from __future__ import annotations

import argparse
import os
import shlex
import stat
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parent
DEFAULT_CONFIG = ROOT / "config.yaml"
DEFAULT_LABS = ROOT / "labs.yaml"
DEFAULT_LAUNCHER = ROOT / "wave-cml2"


def read_yaml(path: Path) -> dict[str, Any]:
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except (OSError, yaml.YAMLError) as exc:
        raise RuntimeError(f"Cannot read {path}: {exc}") from exc
    if not isinstance(data, dict):
        raise RuntimeError(f"{path} must contain a YAML mapping")
    return data


def select_lab(labs: dict[str, Any], wanted: str | None) -> tuple[str, dict[str, Any]]:
    candidates = []
    for lab_id, lab in labs.items():
        if isinstance(lab, dict) and lab.get("enabled"):
            if wanted is None or wanted in (lab_id, lab.get("lab_title")):
                candidates.append((str(lab_id), lab))
    if not candidates:
        hint = f" matching '{wanted}'" if wanted else ""
        raise RuntimeError(f"No enabled CML2 lab{hint}. Run './breakout init <lab>' first.")
    if len(candidates) > 1:
        raise RuntimeError("More than one enabled lab matches; pass its ID or title.")
    return candidates[0]


def console_nodes(lab: dict[str, Any]) -> list[tuple[str, int]]:
    result: list[tuple[str, int]] = []
    for node in (lab.get("nodes") or {}).values():
        if not isinstance(node, dict):
            continue
        label = str(node.get("label", "unnamed"))
        for device in node.get("devices") or []:
            if isinstance(device, dict) and device.get("enabled") and device.get("listen_port"):
                result.append((label, int(device["listen_port"])))
    if not result:
        raise RuntimeError("The selected lab has no enabled serial consoles.")
    return sorted(result, key=lambda item: (item[0].casefold(), item[1]))


def write_launcher(
    path: Path,
    title: str,
    host: str,
    nodes: list[tuple[str, int]],
) -> None:
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by main.py. Starts CML2 serial consoles in Wave Terminal.",
        "set -euo pipefail",
        "SCRIPT_DIR=$(cd -- \"$(dirname -- \"${BASH_SOURCE[0]}\")\" && pwd -P)",
        f"LAB_TITLE={shlex.quote(title)}",
        f"CONSOLE_HOST=${{CONSOLE_HOST:-{shlex.quote(host)}}}",
        "BREAKOUT=\"$SCRIPT_DIR/breakout\"",
        "BREAKOUT_CONFIG=\"$SCRIPT_DIR/config.yaml\"",
        "BREAKOUT_LABS=\"$SCRIPT_DIR/labs.yaml\"",
        "connect() {",
        "  local port=$1",
        "  if command -v telnet >/dev/null 2>&1; then exec telnet \"$CONSOLE_HOST\" \"$port\"; fi",
        "  if command -v nc >/dev/null 2>&1; then exec nc \"$CONSOLE_HOST\" \"$port\"; fi",
        "  if command -v ncat >/dev/null 2>&1; then exec ncat \"$CONSOLE_HOST\" \"$port\"; fi",
        "  echo 'Install telnet or netcat-openbsd to open CML2 consoles.' >&2; exit 127",
        "}",
        "if [[ ${1:-} == --connect ]]; then connect \"${2:?missing port}\"; fi",
        "command -v wsh >/dev/null 2>&1 || { echo 'Run this script from a Wave Terminal block.' >&2; exit 1; }",
        "# Refresh the lab on every normal launch. The guard prevents recursion after",
        "# main.py has rebuilt this file with the current CML2 devices and ports.",
        "if [[ ${CML2_WAVE_REFRESHED:-} != 1 ]]; then",
        "  if [[ -z ${BREAKOUT_PASSWORD:-} ]]; then",
        "    read -r -s -p \"CML2 password for ${BREAKOUT_USERNAME:-admin}: \" BREAKOUT_PASSWORD",
        "    echo",
        "    export BREAKOUT_PASSWORD",
        "  fi",
        "  echo \"Refreshing active devices for CML2 lab: $LAB_TITLE\"",
        "  export CML2_WAVE_REFRESHED=1",
        "  exec python3 \"$SCRIPT_DIR/main.py\" \"$LAB_TITLE\" --init --output \"$SCRIPT_DIR/wave-cml2\" --run",
        "fi",
        "proxy_ready() {",
        "  python3 - \"$CONSOLE_HOST\" \"$1\" <<'PY'",
        "import socket, sys",
        "host, port = sys.argv[1], int(sys.argv[2])",
        "try:",
        "    with socket.create_connection((host, port), timeout=0.25): pass",
        "except OSError: sys.exit(1)",
        "PY",
        "}",
        f"FIRST_PORT={nodes[0][1]}",
        "if ! proxy_ready \"$FIRST_PORT\"; then",
        "  echo 'Starting the CML2 breakout proxy in a Wave block...'",
        "  proxy_command=$(printf 'exec %q -config %q -labs %q -logtostderr run' \"$BREAKOUT\" \"$BREAKOUT_CONFIG\" \"$BREAKOUT_LABS\")",
        "  wsh run -c \"$proxy_command\"",
        "  for _ in {1..20}; do proxy_ready \"$FIRST_PORT\" && break; sleep 0.25; done",
        "  proxy_ready \"$FIRST_PORT\" || { echo 'breakout did not start; check its Wave block and CML2 credentials.' >&2; exit 1; }",
        "fi",
        "echo \"Opening CML2 consoles for: $LAB_TITLE\"",
    ]
    for label, port in nodes:
        lines.append(f'wsh run -c "\\\"$SCRIPT_DIR/wave-cml2\\\" --connect {port}"')
        lines.append(f"echo {shlex.quote(f'  {label}: {host}:{port}')}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("lab", nargs="?", help="enabled CML2 lab ID or title")
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--labs", type=Path, default=DEFAULT_LABS)
    parser.add_argument("--output", type=Path, default=DEFAULT_LAUNCHER)
    parser.add_argument("--run", action="store_true", help="open all consoles immediately in Wave")
    parser.add_argument("--init", action="store_true", help="refresh breakout's labs.yaml before generating")
    args = parser.parse_args()

    if args.init:
        command = [
            str(ROOT / "breakout"),
            "-config", str(args.config),
            "-labs", str(args.labs),
            "-logtostderr",
            "init",
        ]
        if args.lab:
            command.append(args.lab)
        subprocess.run(command, check=True)
    config = read_yaml(args.config)
    labs = read_yaml(args.labs)
    _, lab = select_lab(labs, args.lab)
    # Keep the configured listener family.  In particular, [::1] must not be
    # silently changed to 127.0.0.1 because a host may enforce IPv6-only binds.
    listen_address = str(config.get("listen_address", "")).strip()
    host = "127.0.0.1" if not listen_address else listen_address.strip("[]")
    write_launcher(
        args.output.resolve(),
        str(lab.get("lab_title", "CML2")),
        host,
        console_nodes(lab),
    )
    print(f"Created {args.output} for lab '{lab.get('lab_title')}'.")
    print(f"Run {args.output} from Wave Terminal to start breakout and open the consoles.")
    if args.run:
        if not os.environ.get("WAVETERM_BLOCKID"):
            raise RuntimeError("--run must be used from a Wave Terminal block")
        subprocess.run([str(args.output.resolve())], check=True)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (RuntimeError, subprocess.CalledProcessError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(1)
