annotations:
  - border_color: '#808080FF'
    border_style: ''
    color: '#FFFFFFFF'
    line_end: null
    line_start: null
    thickness: 1
    type: line
    x1: -200.0
    y1: 0.0
    x2: -200.0
    y2: 0.0
    z_index: 0
nodes:
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n0
    image_definition: null
    label: iol-l2-0
    node_definition: ioll2-xe
    parameters: {}
    ram: null
    tags: []
    x: -200
    y: 0
    interfaces:
      - id: i0
        label: Loopback0
        type: loopback
      - id: i1
        label: Ethernet0/0
        slot: 0
        type: physical
      - id: i2
        label: Ethernet0/1
        slot: 1
        type: physical
      - id: i3
        label: Ethernet0/2
        slot: 2
        type: physical
      - id: i4
        label: Ethernet0/3
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n1
    image_definition: null
    label: iol-l2-1
    node_definition: ioll2-xe
    parameters: {}
    ram: null
    tags: []
    x: 0
    y: 0
    interfaces:
      - id: i0
        label: Loopback0
        type: loopback
      - id: i1
        label: Ethernet0/0
        slot: 0
        type: physical
      - id: i2
        label: Ethernet0/1
        slot: 1
        type: physical
      - id: i3
        label: Ethernet0/2
        slot: 2
        type: physical
      - id: i4
        label: Ethernet0/3
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n2
    image_definition: null
    label: desktop-0
    node_definition: desktop
    parameters: {}
    ram: null
    tags: []
    x: -360
    y: 80
    interfaces:
      - id: i0
        label: eth0
        slot: 0
        type: physical
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n3
    image_definition: null
    label: desktop-1
    node_definition: desktop
    parameters: {}
    ram: null
    tags: []
    x: 160
    y: 80
    interfaces:
      - id: i0
        label: eth0
        slot: 0
        type: physical
links:
  - id: l0
    n1: n0
    n2: n1
    i1: i1
    i2: i1
    conditioning: {}
    label: iol-l2-0-Ethernet0/0<->iol-l2-1-Ethernet0/0
  - id: l1
    n1: n2
    n2: n0
    i1: i0
    i2: i2
    conditioning: {}
    label: desktop-0-eth0<->iol-l2-0-Ethernet0/1
  - id: l2
    n1: n3
    n2: n1
    i1: i0
    i2: i2
    conditioning: {}
    label: desktop-1-eth0<->iol-l2-1-Ethernet0/1
lab:
  description: |-
    2.2 Configure and verify interswitch connectivity
    2.2.a Trunk ports
    2.2.b 802.1Q
    2.2.c Native VLAN

    CML ver 2.7
  notes: |-
    Add two IOLL2 switches and two clients

    Connect both switches together and form a trunk

    Connect one client to each switch

    Assign an Ip address to each client and verify connectivity

    Create a vlan named "vlan 10"

    Add ports where each client is connected to vlan 10

    Verify connectivity by pinging each client
  title: 2.2 Configure and verify interswitch connectivity
  version: 0.2.2
