annotations:
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: 192.168.200.0/24
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -240.0
    y1: -160.0
    z_index: 0
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: '.1'
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -280.0
    y1: -160.0
    z_index: 1
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: '.2'
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -40.0
    y1: -160.0
    z_index: 2
nodes:
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |-
          Building configuration...


          Current configuration : 3057 bytes
          !
          ! Last configuration change at 17:44:44 UTC Fri May 17 2024
          !
          version 15.9
          service timestamps debug datetime msec
          service timestamps log datetime msec
          no service password-encryption
          !
          hostname R1
          !
          boot-start-marker
          boot-end-marker
          !
          !
          no logging console
          !
          no aaa new-model
          !
          !
          !
          mmi polling-interval 60
          no mmi auto-configure
          no mmi pvc
          mmi snmp-timeout 180
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          ip domain name cisco.com
          ip cef
          no ipv6 cef
          !
          multilink bundle-name authenticated
          !
          !
          !
          !
          username admin password 0 cisco
          !
          redundancy
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          interface GigabitEthernet0/0
           ip address 192.168.200.1 255.255.255.0
           duplex auto
           speed auto
           media-type rj45
          !
          interface GigabitEthernet0/1
           no ip address
           shutdown
           duplex auto
           speed auto
           media-type rj45
          !
          interface GigabitEthernet0/2
           no ip address
           shutdown
           duplex auto
           speed auto
           media-type rj45
          !
          interface GigabitEthernet0/3
           no ip address
           shutdown
           duplex auto
           speed auto
           media-type rj45
          !
          ip forward-protocol nd
          !
          !
          no ip http server
          no ip http secure-server
          !
          ipv6 ioam timestamp
          !
          !
          !
          control-plane
          !
          banner exec ^C
          **************************************************************************
          * IOSv is strictly limited to use for evaluation, demonstration and IOS  *
          * education. IOSv is provided as-is and is not supported by Cisco's      *
          * Technical Advisory Center. Any use or disclosure, in whole or in part, *
          * of the IOSv Software or Documentation to any third party for any       *
          * purposes is expressly prohibited except as otherwise authorized by     *
          * Cisco in writing.                                                      *
          **************************************************************************^C
          banner incoming ^C
          **************************************************************************
          * IOSv is strictly limited to use for evaluation, demonstration and IOS  *
          * education. IOSv is provided as-is and is not supported by Cisco's      *
          * Technical Advisory Center. Any use or disclosure, in whole or in part, *
          * of the IOSv Software or Documentation to any third party for any       *
          * purposes is expressly prohibited except as otherwise authorized by     *
          * Cisco in writing.                                                      *
          **************************************************************************^C
          banner login ^C
          **************************************************************************
          * IOSv is strictly limited to use for evaluation, demonstration and IOS  *
          * education. IOSv is provided as-is and is not supported by Cisco's      *
          * Technical Advisory Center. Any use or disclosure, in whole or in part, *
          * of the IOSv Software or Documentation to any third party for any       *
          * purposes is expressly prohibited except as otherwise authorized by     *
          * Cisco in writing.                                                      *
          **************************************************************************^C
          !
          line con 0
           exec-timeout 0 0
          line aux 0
          line vty 0 4
           exec-timeout 0 0
           login local
           transport input ssh
          !
          no scheduler allocate
          !
          end
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n0
    image_definition: null
    label: R1
    node_definition: iosv
    parameters: {}
    ram: null
    tags: []
    x: -280
    y: -120
    interfaces:
      - id: i0
        label: Loopback0
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet0/1
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet0/2
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet0/3
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |-
          Building configuration...


          Current configuration : 3057 bytes
          !
          ! Last configuration change at 17:44:32 UTC Fri May 17 2024
          !
          version 15.9
          service timestamps debug datetime msec
          service timestamps log datetime msec
          no service password-encryption
          !
          hostname R2
          !
          boot-start-marker
          boot-end-marker
          !
          !
          no logging console
          !
          no aaa new-model
          !
          !
          !
          mmi polling-interval 60
          no mmi auto-configure
          no mmi pvc
          mmi snmp-timeout 180
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          ip domain name cisco.com
          ip cef
          no ipv6 cef
          !
          multilink bundle-name authenticated
          !
          !
          !
          !
          username admin password 0 cisco
          !
          redundancy
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          interface GigabitEthernet0/0
           ip address 192.168.200.2 255.255.255.0
           duplex auto
           speed auto
           media-type rj45
          !
          interface GigabitEthernet0/1
           no ip address
           shutdown
           duplex auto
           speed auto
           media-type rj45
          !
          interface GigabitEthernet0/2
           no ip address
           shutdown
           duplex auto
           speed auto
           media-type rj45
          !
          interface GigabitEthernet0/3
           no ip address
           shutdown
           duplex auto
           speed auto
           media-type rj45
          !
          ip forward-protocol nd
          !
          !
          no ip http server
          no ip http secure-server
          !
          ipv6 ioam timestamp
          !
          !
          !
          control-plane
          !
          banner exec ^C
          **************************************************************************
          * IOSv is strictly limited to use for evaluation, demonstration and IOS  *
          * education. IOSv is provided as-is and is not supported by Cisco's      *
          * Technical Advisory Center. Any use or disclosure, in whole or in part, *
          * of the IOSv Software or Documentation to any third party for any       *
          * purposes is expressly prohibited except as otherwise authorized by     *
          * Cisco in writing.                                                      *
          **************************************************************************^C
          banner incoming ^C
          **************************************************************************
          * IOSv is strictly limited to use for evaluation, demonstration and IOS  *
          * education. IOSv is provided as-is and is not supported by Cisco's      *
          * Technical Advisory Center. Any use or disclosure, in whole or in part, *
          * of the IOSv Software or Documentation to any third party for any       *
          * purposes is expressly prohibited except as otherwise authorized by     *
          * Cisco in writing.                                                      *
          **************************************************************************^C
          banner login ^C
          **************************************************************************
          * IOSv is strictly limited to use for evaluation, demonstration and IOS  *
          * education. IOSv is provided as-is and is not supported by Cisco's      *
          * Technical Advisory Center. Any use or disclosure, in whole or in part, *
          * of the IOSv Software or Documentation to any third party for any       *
          * purposes is expressly prohibited except as otherwise authorized by     *
          * Cisco in writing.                                                      *
          **************************************************************************^C
          !
          line con 0
           exec-timeout 0 0
          line aux 0
          line vty 0 4
           exec-timeout 0 0
           login local
           transport input ssh
          !
          no scheduler allocate
          !
          end
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n1
    image_definition: null
    label: R2
    node_definition: iosv
    parameters: {}
    ram: null
    tags: []
    x: -40
    y: -120
    interfaces:
      - id: i0
        label: Loopback0
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet0/1
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet0/2
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet0/3
        slot: 3
        type: physical
links:
  - id: l0
    n1: n0
    n2: n1
    i1: i1
    i2: i1
    conditioning: {}
    label: iosv-0-GigabitEthernet0/0<->iosv-1-GigabitEthernet0/0
lab:
  description: 'version: 0.4.8'
  notes: |2-
        # Domain:4 Configure network devices for remote access using SSH
        In this lab you will configure SSH secure remote access of Router R2.
        This lab focuses on task 4.8 from the CCNA Exam Blueprint. The Routers have no passwords.
        Consult the topology map for addressing.

        To complete this lab, do the following:
        - Configure SSh on both routers
          - In config terminal set the hostname and domain name of the routers.
          - Generate the RSA Kypair by using command crypto key generate rsa.
          - Configure VTY Lines to use SSH only
          - Configure Username and password

        - Verify SSH remote access from each router
          - use command ssh -l username password comand to access other router

        ```
    R1#ssh -l admin 192.168.200.2

    **************************************************************************
    * IOSv is strictly limited to use for evaluation, demonstration and IOS  *
    * education. IOSv is provided as-is and is not supported by Cisco's      *
    * Technical Advisory Center. Any use or disclosure, in whole or in part, *
    * of the IOSv Software or Documentation to any third party for any       *
    * purposes is expressly prohibited except as otherwise authorized by     *
    * Cisco in writing.                                                      *
    **************************************************************************
    Password:



    **************************************************************************
    * IOSv is strictly limited to use for evaluation, demonstration and IOS  *
    * education. IOSv is provided as-is and is not supported by Cisco's      *
    * Technical Advisory Center. Any use or disclosure, in whole or in part, *
    * of the IOSv Software or Documentation to any third party for any       *
    * purposes is expressly prohibited except as otherwise authorized by     *
    * Cisco in writing.                                                      *
    **************************************************************************
    R2>
        ```
  title: Domain_4_Configure_network_devices_using_SSH_(solution)
  version: 0.2.2
