annotations: []
nodes:
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |-
          Building configuration...

          Current configuration : 942 bytes
          !
          ! Last configuration change at 16:27:40 UTC Fri May 17 2024
          !
          version 17.12
          service timestamps debug datetime msec
          service timestamps log datetime msec
          !
          hostname R1
          !
          boot-start-marker
          boot-end-marker
          !
          !
          no logging console
          no aaa new-model
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          ip cef
          login on-success log
          no ipv6 cef
          !
          !
          !
          !
          !
          !
          !
          !
          multilink bundle-name authenticated
          !
          !
          !
          !
          !
          memory free low-watermark processor 81225
          !
          !
          spanning-tree mode rapid-pvst
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          interface Ethernet0/0
           no ip address
           shutdown
          !
          interface Ethernet0/1
           no ip address
           shutdown
          !
          interface Ethernet0/2
           no ip address
           shutdown
          !
          interface Ethernet0/3
           no ip address
           shutdown
          !
          ip forward-protocol nd
          !
          !
          ip http server
          ip http secure-server
          ip ssh bulk-mode 131072
          !
          !
          !
          !
          !
          control-plane
          !
          !
          !
          line con 0
           exec-timeout 0 0
           logging synchronous
          line aux 0
          line vty 0 4
           exec-timeout 0 0
           login
           transport input ssh
          !
          !
          !
          !
          end
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n0
    image_definition: null
    label: iol-0
    node_definition: iol-xe
    parameters: {}
    ram: null
    tags: []
    x: -120
    y: -200
    interfaces:
      - id: i0
        label: Loopback0
        type: loopback
      - id: i1
        label: Ethernet0/0
        slot: 0
        type: physical
      - id: i2
        label: Ethernet0/1
        slot: 1
        type: physical
      - id: i3
        label: Ethernet0/2
        slot: 2
        type: physical
      - id: i4
        label: Ethernet0/3
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |-
          Building configuration...

          Current configuration : 938 bytes
          !
          ! Last configuration change at 16:28:19 UTC Fri May 17 2024
          !
          version 17.12
          service timestamps debug datetime msec
          service timestamps log datetime msec
          !
          hostname SW1
          !
          boot-start-marker
          boot-end-marker
          !
          !
          no logging console
          no aaa new-model
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          ip audit notify log
          ip audit po max-events 100
          ip cef
          login on-success log
          no ipv6 cef
          !
          !
          !
          !
          !
          !
          !
          vtp version 1
          multilink bundle-name authenticated
          !
          !
          !
          !
          memory free low-watermark processor 80589
          !
          !
          spanning-tree mode rapid-pvst
          spanning-tree extend system-id
          !
          !
          vlan internal allocation policy ascending
          !
          !
          !
          !
          !
          interface Ethernet0/0
          !
          interface Ethernet0/1
          !
          interface Ethernet0/2
          !
          interface Ethernet0/3
          !
          ip forward-protocol nd
          !
          !
          ip http server
          ip http secure-server
          ip ssh bulk-mode 131072
          !
          !
          !
          !
          !
          !
          control-plane
          !
          !
          !
          line con 0
           exec-timeout 0 0
           logging synchronous
          line aux 0
          line vty 0 4
           exec-timeout 0 0
           login
           transport input ssh
          !
          !
          end
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n1
    image_definition: null
    label: iol-l2-0
    node_definition: ioll2-xe
    parameters: {}
    ram: null
    tags: []
    x: -320
    y: 160
    interfaces:
      - id: i0
        label: Loopback0
        type: loopback
      - id: i1
        label: Ethernet0/0
        slot: 0
        type: physical
      - id: i2
        label: Ethernet0/1
        slot: 1
        type: physical
      - id: i3
        label: Ethernet0/2
        slot: 2
        type: physical
      - id: i4
        label: Ethernet0/3
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |-
          Building configuration...

          Current configuration : 938 bytes
          !
          ! Last configuration change at 16:27:47 UTC Fri May 17 2024
          !
          version 17.12
          service timestamps debug datetime msec
          service timestamps log datetime msec
          !
          hostname SW2
          !
          boot-start-marker
          boot-end-marker
          !
          !
          no logging console
          no aaa new-model
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          ip audit notify log
          ip audit po max-events 100
          ip cef
          login on-success log
          no ipv6 cef
          !
          !
          !
          !
          !
          !
          !
          vtp version 1
          multilink bundle-name authenticated
          !
          !
          !
          !
          memory free low-watermark processor 80589
          !
          !
          spanning-tree mode rapid-pvst
          spanning-tree extend system-id
          !
          !
          vlan internal allocation policy ascending
          !
          !
          !
          !
          !
          interface Ethernet0/0
          !
          interface Ethernet0/1
          !
          interface Ethernet0/2
          !
          interface Ethernet0/3
          !
          ip forward-protocol nd
          !
          !
          ip http server
          ip http secure-server
          ip ssh bulk-mode 131072
          !
          !
          !
          !
          !
          !
          control-plane
          !
          !
          !
          line con 0
           exec-timeout 0 0
           logging synchronous
          line aux 0
          line vty 0 4
           exec-timeout 0 0
           login
           transport input ssh
          !
          !
          end
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n2
    image_definition: null
    label: iol-l2-1
    node_definition: ioll2-xe
    parameters: {}
    ram: null
    tags: []
    x: -120
    y: 80
    interfaces:
      - id: i0
        label: Loopback0
        type: loopback
      - id: i1
        label: Ethernet0/0
        slot: 0
        type: physical
      - id: i2
        label: Ethernet0/1
        slot: 1
        type: physical
      - id: i3
        label: Ethernet0/2
        slot: 2
        type: physical
      - id: i4
        label: Ethernet0/3
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |-
          Building configuration...

          Current configuration : 938 bytes
          !
          ! Last configuration change at 16:29:05 UTC Fri May 17 2024
          !
          version 17.12
          service timestamps debug datetime msec
          service timestamps log datetime msec
          !
          hostname SW3
          !
          boot-start-marker
          boot-end-marker
          !
          !
          no logging console
          no aaa new-model
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          ip audit notify log
          ip audit po max-events 100
          ip cef
          login on-success log
          no ipv6 cef
          !
          !
          !
          !
          !
          !
          !
          vtp version 1
          multilink bundle-name authenticated
          !
          !
          !
          !
          memory free low-watermark processor 80589
          !
          !
          spanning-tree mode rapid-pvst
          spanning-tree extend system-id
          !
          !
          vlan internal allocation policy ascending
          !
          !
          !
          !
          !
          interface Ethernet0/0
          !
          interface Ethernet0/1
          !
          interface Ethernet0/2
          !
          interface Ethernet0/3
          !
          ip forward-protocol nd
          !
          !
          ip http server
          ip http secure-server
          ip ssh bulk-mode 131072
          !
          !
          !
          !
          !
          !
          control-plane
          !
          !
          !
          line con 0
           exec-timeout 0 0
           logging synchronous
          line aux 0
          line vty 0 4
           exec-timeout 0 0
           login
           transport input ssh
          !
          !
          end
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n3
    image_definition: null
    label: iol-l2-2
    node_definition: ioll2-xe
    parameters: {}
    ram: null
    tags: []
    x: 80
    y: 160
    interfaces:
      - id: i0
        label: Loopback0
        type: loopback
      - id: i1
        label: Ethernet0/0
        slot: 0
        type: physical
      - id: i2
        label: Ethernet0/1
        slot: 1
        type: physical
      - id: i3
        label: Ethernet0/2
        slot: 2
        type: physical
      - id: i4
        label: Ethernet0/3
        slot: 3
        type: physical
links:
  - id: l0
    n1: n0
    n2: n2
    i1: i1
    i2: i1
    conditioning: {}
    label: iol-0-Ethernet0/0<->iol-l2-1-Ethernet0/0
  - id: l1
    n1: n1
    n2: n2
    i1: i1
    i2: i2
    conditioning: {}
    label: iol-l2-0-Ethernet0/0<->iol-l2-1-Ethernet0/1
  - id: l2
    n1: n3
    n2: n2
    i1: i1
    i2: i3
    conditioning: {}
    label: iol-l2-2-Ethernet0/0<->iol-l2-1-Ethernet0/2
lab:
  description: 0.2.2
  notes: |-
    # Domain 2:  Disable and Enable Cisco Discovery Protocol
        In this lab you will disable the default enabled CDP on interface level and verify the configuration results.
        This lab focuses on task 2.3 from the CCNA Exam Blueprint.The switches and router have no passwords.
        Consult the topology map for addressing.

        To complete this lab, do the following:
        - Disable  CDP on SW2 interface G0/0
          - Go to interface G0/0 of SW2 n config terminal and enter command no cdp enable
          - Wait for 60 secs to take the changes take effect

        - Verify that CDP is disabled on SW2 port G0/0
          - Take console of R1 and give command in Privileged mode show cdp neighbors
          - SW2 neighbor would not be shown
  title: Doman_2_CDP_Configuration
  version: 0.2.2
