annotations:
  - border_color: '#808080FF'
    border_radius: 0
    border_style: ''
    color: '#BBEA9A'
    thickness: 1
    type: rectangle
    x1: -760.0
    y1: -200.0
    x2: 720.0
    y2: 280.0
    z_index: 0
  - border_color: '#00000000'
    border_style: ''
    color: '#0A0000'
    rotation: 0
    text_bold: true
    text_content: CDP
    text_font: cursive
    text_italic: false
    text_size: 20
    text_unit: pt
    thickness: 1
    type: text
    x1: -680.0
    y1: -160.0
    z_index: 1
  - border_color: '#00000000'
    border_style: ''
    color: '#080000'
    rotation: 0
    text_bold: false
    text_content: LLDP
    text_font: cursive
    text_italic: false
    text_size: 20
    text_unit: pt
    thickness: 1
    type: text
    x1: -200.0
    y1: -160.0
    z_index: 2
  - border_color: '#808080FF'
    border_style: ''
    color: '#F0BDBD'
    thickness: 1
    type: ellipse
    x1: -120.0
    y1: 220.0
    x2: 120.0
    y2: 100.0
    z_index: 3
  - border_color: '#00000000'
    border_style: ''
    color: '#080000'
    rotation: 0
    text_bold: true
    text_content: Managment Desktop
    text_font: cursive
    text_italic: false
    text_size: 13
    text_unit: pt
    thickness: 1
    type: text
    x1: -200.0
    y1: 240.0
    z_index: 4
nodes:
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n0
    image_definition: null
    label: iosv-0
    node_definition: iosv
    parameters: {}
    ram: null
    tags: []
    x: -400
    y: -160
    interfaces:
      - id: i0
        label: Loopback0
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet0/1
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet0/2
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet0/3
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n1
    image_definition: null
    label: iosvl2-0
    node_definition: iosvl2
    parameters: {}
    ram: null
    tags: []
    x: -120
    y: 40
    interfaces:
      - id: i0
        label: Loopback0
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet0/1
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet0/2
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet0/3
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n2
    image_definition: null
    label: desktop-0
    node_definition: desktop
    parameters: {}
    ram: null
    tags: []
    x: -120
    y: 200
    interfaces:
      - id: i0
        label: eth0
        slot: 0
        type: physical
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n3
    image_definition: null
    label: iol-l2-0
    node_definition: ioll2-xe
    parameters: {}
    ram: null
    tags: []
    x: -680
    y: 40
    interfaces:
      - id: i0
        label: Loopback0
        type: loopback
      - id: i1
        label: Ethernet0/0
        slot: 0
        type: physical
      - id: i2
        label: Ethernet0/1
        slot: 1
        type: physical
      - id: i3
        label: Ethernet0/2
        slot: 2
        type: physical
      - id: i4
        label: Ethernet0/3
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n4
    image_definition: null
    label: iol-l2-1
    node_definition: ioll2-xe
    parameters: {}
    ram: null
    tags: []
    x: -400
    y: 40
    interfaces:
      - id: i0
        label: Loopback0
        type: loopback
      - id: i1
        label: Ethernet0/0
        slot: 0
        type: physical
      - id: i2
        label: Ethernet0/1
        slot: 1
        type: physical
      - id: i3
        label: Ethernet0/2
        slot: 2
        type: physical
      - id: i4
        label: Ethernet0/3
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n5
    image_definition: null
    label: ext-conn-0
    node_definition: external_connector
    parameters: {}
    ram: null
    tags: []
    x: -400
    y: -320
    interfaces:
      - id: i0
        label: port
        slot: 0
        type: physical
links:
  - id: l0
    n1: n0
    n2: n1
    i1: i1
    i2: i1
    conditioning: {}
    label: iosv-0-GigabitEthernet0/0<->iosvl2-0-GigabitEthernet0/0
  - id: l1
    n1: n1
    n2: n2
    i1: i2
    i2: i0
    conditioning: {}
    label: iosvl2-0-GigabitEthernet0/1<->desktop-0-eth0
  - id: l2
    n1: n0
    n2: n3
    i1: i2
    i2: i1
    conditioning: {}
    label: iosv-0-GigabitEthernet0/1<->iol-l2-0-Ethernet0/0
  - id: l3
    n1: n3
    n2: n4
    i1: i2
    i2: i1
    conditioning: {}
    label: iol-l2-0-Ethernet0/1<->iol-l2-1-Ethernet0/0
  - id: l4
    n1: n4
    n2: n1
    i1: i2
    i2: i3
    conditioning: {}
    label: iol-l2-1-Ethernet0/1<->iosvl2-0-GigabitEthernet0/2
  - id: l5
    n1: n0
    n2: n5
    i1: i3
    i2: i0
    conditioning: {}
    label: iosv-0-GigabitEthernet0/2<->ext-conn-0-port
lab:
  description: |-
    CDP and LLDP are like friendly messages that network devices send to each other to introduce themselves and share information.
    CDP is like a postcard that Cisco devices use to say "Hello, I'm a Cisco device!" It also tells other Cisco devices nearby about its name, the type of device it is, and how it's connected.
    LLDP is similar, but it's like a universal postcard that all kinds of devices can use. It sends out messages saying "Hi, I'm here!" and shares basic information about the device, like its name, what it is, and how it's connected to the network.
    So, CDP and LLDP are both ways for devices on a network to be friendly and introduce themselves, helping to keep everything connected smoothly.
  notes: ''
  title: Task-2.3[Configure and verify Layer 2 discovery protocols]
  version: 0.2.2
